name: release terraform version

on:
  push:
    branches:
      - master
    workflow_dispatch:
permissions: write-all

jobs:
  run-ci:
    name: release the terraform version
    if: "!contains(github.event.head_commit.message, 'chore(versionbump)')"
    runs-on: ubuntu-latest

    steps:
      # clone the code repo
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: 'chore(versionbump): new version: {version}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          skip-on-empty: 'true'
